repos:
  - go-sdk
  - go-sdk-contrib

approvers:
  - bbland1
  - beeme1mr
  - agentgonzo
  - thisthat

maintainers:
  - AlexsJones
  - bacherfl
  - davejohnston
  - james-milligan
  - Kavindu-Dodan
  - skyerus
  - sahidvelji
  - thomaspoignant
  - toddbaert

admins: []
